2025-03-06 23:58:26,377 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.130.49.36:43197'
2025-03-06 23:58:26,377 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.130.49.36:33041'
2025-03-06 23:58:27,764 - distributed.worker - INFO -       Start worker at:   tcp://10.130.49.36:44533
2025-03-06 23:58:27,764 - distributed.worker - INFO -          Listening to:   tcp://10.130.49.36:44533
2025-03-06 23:58:27,765 - distributed.worker - INFO -           Worker name:             SLURMCluster-1
2025-03-06 23:58:27,765 - distributed.worker - INFO -          dashboard at:         10.130.49.36:39667
2025-03-06 23:58:27,765 - distributed.worker - INFO - Waiting to connect to:  tcp://10.130.56.192:33955
2025-03-06 23:58:27,765 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 23:58:27,765 - distributed.worker - INFO -               Threads:                          5
2025-03-06 23:58:27,765 - distributed.worker - INFO -                Memory:                 488.28 MiB
2025-03-06 23:58:27,765 - distributed.worker - INFO -       Local Directory: /tmp/tmp-g88077/dask-scratch-space/worker-kytsk3ht
2025-03-06 23:58:27,765 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 23:58:27,791 - distributed.worker - INFO -       Start worker at:   tcp://10.130.49.36:38255
2025-03-06 23:58:27,791 - distributed.worker - INFO -          Listening to:   tcp://10.130.49.36:38255
2025-03-06 23:58:27,791 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2025-03-06 23:58:27,791 - distributed.worker - INFO -          dashboard at:         10.130.49.36:38979
2025-03-06 23:58:27,791 - distributed.worker - INFO - Waiting to connect to:  tcp://10.130.56.192:33955
2025-03-06 23:58:27,791 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 23:58:27,791 - distributed.worker - INFO -               Threads:                          5
2025-03-06 23:58:27,791 - distributed.worker - INFO -                Memory:                 488.28 MiB
2025-03-06 23:58:27,792 - distributed.worker - INFO -       Local Directory: /tmp/tmp-g88077/dask-scratch-space/worker-iy6f7pb4
2025-03-06 23:58:27,792 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 23:58:28,327 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-03-06 23:58:28,327 - distributed.worker - INFO -         Registered to:  tcp://10.130.56.192:33955
2025-03-06 23:58:28,327 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 23:58:28,328 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-03-06 23:58:28,328 - distributed.core - INFO - Starting established connection to tcp://10.130.56.192:33955
2025-03-06 23:58:28,328 - distributed.worker - INFO -         Registered to:  tcp://10.130.56.192:33955
2025-03-06 23:58:28,328 - distributed.worker - INFO - -------------------------------------------------
2025-03-06 23:58:28,329 - distributed.core - INFO - Starting established connection to tcp://10.130.56.192:33955
slurmstepd: error: *** JOB 51520900 ON crcn0266 CANCELLED AT 2025-03-06T23:58:29 ***
2025-03-06 23:58:29,127 - distributed.worker - INFO - Stopping worker at tcp://10.130.49.36:38255. Reason: scheduler-close
2025-03-06 23:58:29,127 - distributed.worker - INFO - Stopping worker at tcp://10.130.49.36:44533. Reason: scheduler-close
slurmstepd: error: *** JOB 51520901 ON crcn0266 CANCELLED AT 2025-03-06T23:58:29 ***
2025-03-06 23:58:29,128 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.130.49.36:49820 remote=tcp://10.130.56.192:33955>
Traceback (most recent call last):
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
             ^^^^^^^^^^
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.130.49.36:49820 remote=tcp://10.130.56.192:33955>: Stream is closed
2025-03-06 23:58:29,128 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.130.49.36:49812 remote=tcp://10.130.56.192:33955>
Traceback (most recent call last):
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
             ^^^^^^^^^^
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/scratch/users/g88077/python_forge/envs/uqhpc/lib/python3.12/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.130.49.36:49812 remote=tcp://10.130.56.192:33955>: Stream is closed
2025-03-06 23:58:29,131 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.130.49.36:33041'. Reason: scheduler-close
2025-03-06 23:58:29,132 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.130.49.36:43197'. Reason: scheduler-close
2025-03-06 23:58:29,133 - distributed.core - INFO - Received 'close-stream' from tcp://10.130.56.192:33955; closing.
2025-03-06 23:58:29,133 - distributed.nanny - INFO - Worker closed
2025-03-06 23:58:29,134 - distributed.core - INFO - Received 'close-stream' from tcp://10.130.56.192:33955; closing.
2025-03-06 23:58:29,134 - distributed.nanny - INFO - Worker closed
